		man(IOS)                    Specification Document                      man(SEO)



NAME
view-will show all the objects, doors, etc of the room where the user is.

SYNOPSIS
       view [option] [file] 
	   

DESCRIPTION
	This command will show as the command ls all the elements of the room (file) for the user. 
	
	-r Only see directory 

SEE ALSO
	use(), man().
	
REPORTING BUGS
	No bugs reported.
       
AUTHOR
	  Written by IOS group
	  

	  




