man(IOS)                    Specification Document                      man(SEO)



NAME
       Leave- you can exit when you want with the facility of saving where you are and what you have obtained. 

SYNOPSIS
       Leave [] [] … or Pause [][] …

DESCRIPTION
	Prompts the user with the option to resume the game or quit it. This commands pauses the timer of the game.

SEE ALSO
	StoreMoves(), view().
	
REPORTING BUGS
No bugs reported.
       
AUTHOR
	  Written by IOS group


