man(IOS)                    Specification Document                      man(SEO)



NAME
       PickUp- these commands help the user to get the  object of the  rooms (files). 

SYNOPSIS
       PickUp [object]

DESCRIPTION
	Adds a tool placed in the current room (or by interaction with an npc or object) into the inventory of the player, and removes the tool from its original place.           

SEE ALSO
	inv(), Leave().

REPORTING BUGS
	No bugs reported.
       
AUTHOR
	  Written by IOS group

