


NAME

	time- shows the time you still have to play

SYNOPSIS
	time

DESCRIPTION

	This command shows the player the time he has to finish the game. The timer will start at the same time that the user types the play comand. The timer goes down until the end, when is at the end the game will be finished and the player eliminated if they do not win. 


SEE ALSO

REPORTING BUGS
      No bugs detected

AUTHOR
	  Written by IOS group

